module.exports = {
  FLUTTERWAVE_PUBLIC_KEY: process.env.FLUTTERWAVE_PUBLIC_KEY || '',
  FLUTTERWAVE_SECRET_KEY: process.env.FLUTTERWAVE_SECRET_KEY || '',
  FLUTTERWAVE_ENCRYPTED_KEY: process.env.FLUTTERWAVE_ENCRYPTED_KEY || '',
  FLUTTERWAVE_MERCHANT_KEY: process.env.FLUTTERWAVE_MERCHANT_KEY || '',
  FLUTTERWAVE_ENCRYPTION_KEY: process.env.FLUTTERWAVE_ENCRYPTION_KEY || '',
  FLUTTERWAVE_PREFIX: process.env.FLUTTERWAVE_PREFIX || 'FM',
  FLUTTERWAVE_ENVIRONMENT: process.env.FLUTTERWAVE_ENVIRONMENT || 'sandbox',
  FLUTTERWAVE_BASE_URL: process.env.FLUTTERWAVE_BASE_URL || 'https://api.flutterwave.com/v3',
  FLUTTERWAVE_TRANSACTION_URL: process.env.FLUTTERWAVE_TRANSACTION_URL || 'https://api.flutterwave.com/v3/transactions',
  FLUTTERWAVE_CALLBACK_URL: process.env.FLUTTERWAVE_CALLBACK_URL || 'http://localhost:3001/api/payment/callback'
};
